apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: namenode-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hadoop-namenode
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hadoop-datanode
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hadoop-historyserver
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
